# Stage 1: Build environment
FROM node:14-alpine as builder

# Set the working directory inside the container
WORKDIR /fontelar_christma_coding_assignment12

# Create site directory
RUN mkdir fontelar_christma_site

# Navigate to the site directory
WORKDIR /fontelar_christma_coding_assignment12/fontelar_christma_site

# Copy package.json and package-lock.json to container
COPY package*.json ./

# Install dependencies
RUN npm install

# Expose port 8083 to allow outside access /  Expose the port the app runs on
EXPOSE 8083

# Set the PORT environment variable
ENV PORT=8083


