FROM node:16-slim

# Navigate to the site directory
WORKDIR /fontelar_christma_coding_assignment12/fontelar_christma_ui_garden

# Copy package.json and package-lock.json to the working directory
COPY package*.json .

# Install dependencies in a way suitable for CI
RUN CI=true npm install

# Copy the rest of the application source code from the host machine to the working directory
COPY . .

# Since this is a CI environment, there's no need to start the service.
CMD ["npm", "run", "ci:test"]
