name: CI Pipeline
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          - uses: actions/checkout@v2
          - name: Setup Node.js
            uses: actions/setup-node@v2
            with:
              node-version: '20.9.0'
              npm-version: '10.3.0'
          - name: Install Dependencies
            run: npm install
          - name: Install Jest Globally
            run: npm install -g jest
          - name: Run Tests
            run: jest
